# Generated by Django 6.0.3 on 2026-03-20 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('flat', 'Flat Amount')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active_from', models.DateTimeField()),
                ('active_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('usage_limit', models.IntegerField(blank=True, help_text='Maximum number of times this discount can be used', null=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='discounts', to='catalog.category')),
                ('products', models.ManyToManyField(blank=True, related_name='discounts', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('limit_per_user', models.IntegerField(blank=True, help_text='Maximum uses per user', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_rules', to='catalog.category')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='promotions.discount')),
            ],
        ),
    ]
